name: Infra checks
on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate docker-compose
        run: docker compose -f docker/docker-compose.yml config -q
      - name: Terraform fmt check
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
      - run: terraform -chdir=terraform fmt -check -recursive || true
      - name: Kubeconform manifests
        run: |
          curl -sSL https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xz
          ./kubeconform -strict -ignore-missing-schemas k8s/base/*.yaml || true
